apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: threescale-auth
spec:
  url: oci://registry.redhat.io/openshift-service-mesh/3scale-auth-wasm-rhel8:0.0.1
  phase: AUTHZ
  priority: 100
  selector:
    matchLabels:
      app: productpage
  pluginConfig:
    api: v1
    system:
      name: system-name
      upstream:
        name: outbound|443||multitenant.3scale.net
        url: https://istiodevel-admin.3scale.net/
        timeout: 5000
      token: atoken
    backend:
      name: backend-name
      upstream:
        name: outbound|443||su1.3scale.net
        url: https://su1.3scale.net/
        timeout: 5000
      extensions:
      - no_body
    services:
    - id: '2555417834780'
      token: service_token
      authorities:
      - "*"
      credentials:
        app_id:
          - header:
              keys:
                - app_id
          - query_string:
              keys:
                - app_id
                - application_id
        app_key:
          - header:
              keys:
                - app_key
          - query_string:
              keys:
                - app_key
                - application_key
        user_key:
          - query_string:
              keys:
                - user_key
          - header:
              keys:
                - user_key
      mapping_rules:
      - method: GET
        pattern: "/"
        usages:
        - name: hits
          delta: 1
      - method: GET
        pattern: "/o{*}c"
        usages:
        - name: oidc
          delta: 1
        - name: hits
          delta: 1
      - method: any
        pattern: "/{anything}?bigsale={*}"
        usages:
        - name: sale
          delta: 5
