version: "2.2"
services:
  ingress:
    image: istio/proxyv2:1.9.8
    entrypoint: /bin/bash -c 'sleep 1 && /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --bootstrap-version 3 --service-cluster $$(domainname) --service-node $$(hostname) --log-level trace'
    volumes:
      - ${ENVOY_DIR:-./envoy}:/etc/envoy/:z,rw
      - ${WASM_FILTER:-./wasm}:/etc/proxy-wasm/:z,rw
    expose:
      - "80"
      - "443"
      - "8080"
      - "8001"
    ports:
      - "8080:80"
      - "8443:443"
      - "9080:8080"
      - "9001:8001"
    scale: 1
    domainname: "ingress"
    networks:
      - ingress
      - mesh
  web:
    image: quay.io/3scale/echoapi:stable
    expose:
      - "9292"
    ports:
      - "9292"
    scale: 1
    domainname: "app"
    networks:
      mesh:
        aliases:
          - app
          - web.app

  keycloak:
    logging:
      driver: none
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    expose:
      - "8080"
      - "8443"
    ports:
      - "18080:8080"
      - "18443:8443"
    domainname: "sso"
    dns: "8.8.8.8"
    networks:
      ingress:
        aliases:
          - sso
          - keycloak.sso
      mesh:

  shell:
    build: ${EXAMPLES_DIR:-./examples}
    image: shell
    volumes:
      - ${EXAMPLES_DIR:-./examples}/:/examples/:z,ro
    command: /bin/bash -c "while true; do sleep 30d; done"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PATH: /usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/examples
    restart: "no"
    networks:
      ingress:
    depends_on:
      keycloak:
        condition: service_started
      ingress:
        condition: service_started

networks:
  ingress:
  mesh:
