name: License Check

on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  licensing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    # Prevent sudden announcement of a new advisory from failing
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
